version: '3'

tasks:
  default:
    desc: "The default task" 
    cmds:
      - go-task run

  run:
    desc: "Run the application"
    cmds:
      - docker compose up -d
      - docker compose exec --env CGO_ENABLED=0 mosdns-dev go build .
      # - docker compose exec --env CGO_ENABLED=0 dhcp-manager-dev go build -o dhcp-manager main.go
      # - docker compose exec dhcp-manager-dev pkill dhcp-manager || true
      # - docker compose exec dhcp-manager-dev ssh root@192.168.100.101 rm -f /tmp/dhcp-manager || true
      # - docker compose exec dhcp-manager-dev scp dhcp-manager root@192.168.100.101:/tmp
      # - docker compose exec dhcp-manager-dev ssh root@192.168.100.101 /tmp/dhcp-manager
  
  # proto:
  #   desc: "Generate protobuf"
  #   cmds:
  #     - docker compose exec dhcp-manager-dev protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./pkg/grpcgen/dhcp-manager.proto

  rebuild-dev-image:
    desc: "Rebuild the development image"
    cmds:
      - docker compose up -d --build