version: '3'

tasks:
  default:
    desc: "The default task" 
    cmds:
      - go-task run

  run:
    desc: "Run the application"
    cmds:
      - docker compose exec mosdns-dev pkill mosdns || true
      - docker compose up -d
      - docker compose exec --env CGO_ENABLED=0 mosdns-dev go build .
      - docker compose exec mosdns-dev ssh root@192.168.100.101 rm -f /tmp/mosdns || true
      - docker compose exec mosdns-dev scp mosdns root@192.168.100.101:/tmp
      - docker compose exec mosdns-dev scp config.yaml root@192.168.100.101:/tmp
      - docker compose exec mosdns-dev ssh root@192.168.100.101 /tmp/mosdns -c /tmp/config.yaml start
  
  # proto:
  #   desc: "Generate protobuf"
  #   cmds:
  #     - docker compose exec mosdns-dev protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative ./pkg/grpcgen/dhcp-manager.proto

  rebuild-dev-image:
    desc: "Rebuild the development image"
    cmds:
      - docker compose up -d --build